create table if not exists "user"
(
    user_id bigint generated by default as identity primary key,
    email     varchar(320) not null,
    login   varchar(200) not null,
    name     varchar(200),
    birthday date
);

create table if not exists "rating_mpa"
(
    rating_id bigint generated by default as identity primary key,
    name     varchar(200) not null
);

create table if not exists "film"
(
    film_id bigint generated by default as identity primary key,
    name     varchar(200) not null,
    description   varchar(200),
    release_date date not null,
    duration int not null,
    rating_id int,
     CONSTRAINT fk_film_rating_id
       FOREIGN KEY(rating_id)
       REFERENCES "rating_mpa"(rating_id)
);

create table if not exists "genre"
(
    genre_id bigint generated by default as identity primary key,
    name     varchar(200) not null
);

create table if not exists "friendship"
(
    friendship_id bigint generated by default as identity primary key,
    user_id     bigint not null,
    friend_id   bigint not null,
    relation_type varchar(200) not null,
    CONSTRAINT fk_friendship_user_id
      FOREIGN KEY(user_id)
      REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_friendship_friend_id
      FOREIGN KEY(friend_id)
      REFERENCES "user"(user_id) ON DELETE CASCADE

);

CREATE UNIQUE INDEX if not exists unique_index_friendship ON "friendship" (user_id, friend_id);

create table if not exists "film_genre"
(
    film_genre_id bigint generated by default as identity primary key,
    film_id     bigint not null,
    genre_id    int not null,
    CONSTRAINT fk_film_genre_film_id
      FOREIGN KEY(film_id)
      REFERENCES "film" ON DELETE CASCADE,
    CONSTRAINT fk_film_genre_genre_id
      FOREIGN KEY(genre_id)
      REFERENCES "genre"(genre_id)
);

CREATE UNIQUE INDEX if not exists unique_index_film_genre ON "film_genre" (film_id, genre_id);

create table if not exists "film_like"
(
    film_like_id bigint generated by default as identity primary key,
    film_id     bigint not null,
    user_id    bigint not null,
    CONSTRAINT fk_film_like_film_id
      FOREIGN KEY(film_id)
      REFERENCES "film"(film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_like_user_id
      FOREIGN KEY(user_id)
      REFERENCES "user"(user_id)
      ON DELETE CASCADE
);

create table if not exists "director"
(
    director_id bigint generated by default as identity primary key,
    name     varchar(200) not null
);

create table if not exists "film_director"
(
    film_director_id bigint generated by default as identity primary key,
    film_id     bigint not null,
    director_id    int not null,
    CONSTRAINT fk_film_director_film_id
      FOREIGN KEY(film_id)
      REFERENCES "film"(film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_director_director_id
      FOREIGN KEY(director_id)
      REFERENCES "director"(director_id)
);